#!/bin/bash
echo "Checking API URL in environment files:"
echo "======================================="
echo ".env file:"
grep VITE_API_URL .env 2>/dev/null || echo "Not found"
echo ""
echo ".env.development file:"
grep VITE_API_URL .env.development 2>/dev/null || echo "Not found"
echo ""
echo ".env.production file:"
grep VITE_API_URL .env.production 2>/dev/null || echo "Not found"
echo ""
echo "Checking if API is accessible:"
echo "======================================="
echo "Port 6093 (correct):"
curl -s http://fred.taile5e8a3.ts.net:6093/health | jq -r .status || echo "Failed"
echo ""
echo "Port 6095 (incorrect - dual GPU):"
curl -s http://fred.taile5e8a3.ts.net:6095/health | jq -r .status || echo "Failed"